version: '2'
services:
  jupyter:
    build:
      context: jupyter
      #dockerfile: pyspark.dockerfile
    volumes:
      - "./jupyter/notebooks:/notebooks"
    ports:
      - "9000:8888"
    depends_on:
      - db
    restart: always
  db:
    build:
      context: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
